### ISSUE TITLE
Cox regression broke with latest StatsModels master

### ISSUE THREAD

**Issue by piever** [JuliaStats/Survival.jl#10]
Not sure what's happening (unfortunately I don't remember any more what manipulations StatsModels does to `fit` before calling `fit` with arrays):

```julia
julia> using Survival, DataFrames, StatsModels

julia> df = DataFrame(x = rand(4), y = EventTime.(rand(4), rand(Bool, 4)))
4×2 DataFrame
│ Row │ x        │ y         │
│     │ Float64  │ EventTim… │
├─────┼──────────┼───────────┤
│ 1   │ 0.827601 │ 0.662955+ │
│ 2   │ 0.909557 │ 0.0749414 │
│ 3   │ 0.379872 │ 0.0578822 │
│ 4   │ 0.122107 │ 0.712976  │

julia> fit(CoxModel, @formula(y ~ x), df)
ERROR: MethodError: no method matching fit(::Type{CoxModel}, ::Array{Float64,2}, ::Array{Float64,2})
Closest candidates are:
  fit(::Type{Histogram}, ::Any...; kwargs...) at /home/pietro/.julia/dev/StatsBase/src/hist.jl:319
  fit(::StatisticalModel, ::Any...) at /home/pietro/.julia/dev/StatsBase/src/statmodels.jl:151
  fit(::Type{T<:RegressionModel}, ::FormulaTerm, ::Any, ::Any...; contrasts, kwargs...) where T<:RegressionModel at /home/pietro/.julia/dev/StatsModels/src/statsmodel.jl:82
  ...
Stacktrace:
 [1] #fit#57(::Dict{Symbol,Any}, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}, ::Function, ::Type{CoxModel}, ::FormulaTerm{Term,Term}, ::DataFrame) at /home/pietro/.julia/dev/StatsModels/src/statsmodel.jl:88
 [2] fit(::Type{CoxModel}, ::FormulaTerm{Term,Term}, ::DataFrame) at /home/pietro/.julia/dev/StatsModels/src/statsmodel.jl:82
 [3] top-level scope at none:0
```

**Comment by ararslan** [comment]
Hm, I probably should have been paying more attention to the details of the changes in https://github.com/JuliaStats/StatsModels.jl/pull/71 so that I would know how to adapt this package. 😬

**Comment by kleinschmidt** [comment]
What's happened here is that the `EventTime` type is treated as a categorical term since it's not `<:Number`.  Teh hacky/quick and dirty way to deal with this is to use `@formula(identity(y) ~ x)`.  That way the `y` vector is copied through unchanged (elementwise).

I think the way to fix this is to define some special handling of these types, either here or in StatsModels itself.  Currently there are only two types of "concrete terms" defined in statsmodels: continuous and categorical.  Maybe a third basic type like `IdentityTerm`, and then define a method for `schema(t::Term, x::AbstractVector{<:EventTime}) = IdentityTerm(t)` in this package.

**Comment by ararslan** [comment]
For now I've opted to add an upper bound on StatsModels to this package.

**Comment by ararslan** [comment]
@kleinschmidt, you said that JuliaStats/StatsModels.jl#106 partially fixes this; what's left to be done? Should this remain open for now?

**Comment by kleinschmidt** [comment]
It's in #17.  Let me double check that it works...
